### PR TITLE
vscode compatibility

### PR DESCRIPTION
**Pull request by sbidoul**
Hi @guewen, here is a couple of commits to enhance compatibility with vscode.

### CODE REVIEW

**Comment by sbidoul** [comment]
cc/ @qgroulard

**Review by guewen — APPROVED** [review]
Not using vscode, but make sense anyway. Thanks!

**Comment by sbidoul** [comment]
Thanks!

> Not using vscode

Was trying it for a young colleague. Must say it's good. I might do some infidelities to my trusty old vim.

**Comment by sbidoul** [comment]
@guewen can you do a quick release?

**Comment by guewen** [comment]
done

**Comment by sbidoul** [comment]
Thanks a lot!

**Pull request merged**
