### PR TITLE
Remove dependency on py lib

### PR DESCRIPTION
**Pull request by guewen**
The py dependency has been removed in pytest:
https://github.com/pytest-dev/pytest/pull/10396

### CODE REVIEW

**Comment by guewen** [comment]
@simahawk @sbidoul

**Review by simahawk — APPROVED** [review]

**Review by sbidoul — APPROVED** [review]
SGTM. 

Want to make a release (also with #49)?

**Review by petrus-v — APPROVED** [review]
Code review and approved by my CI !

**Comment by sbidoul** [comment]
@guewen @simahawk this change makes pytest-odoo require pytest>=7.2, which in turn requires python>=3.7.

**Pull request merged**
