### PR TITLE
Support pytest > 8.0

### PR DESCRIPTION
**Pull request by petrus-v**
Here monkey patching pytest itself to load test odoo test modules forcing odoo namespacing  

this PR is based on #73

### CODE REVIEW

**Comment by petrus-v** [comment]
@simahawk with this version we are not compatible with pytest < 8 (which it doesn't matter) and I haven't limitations that #70  had !

I'll keep in draft I'll like to add some unit test but I've test it on different project without problems ! I'll would be happy to get some other feedbacks.

**Comment by petrus-v** [comment]
unittest has been added !

**Comment by yvaucher** [comment]
Please rebase (seems the commits here are slightly different than in https://github.com/camptocamp/pytest-odoo/pull/73)

**Comment by yvaucher** [comment]
By the way your commit message has some typo on `monkey patching`

**Comment by petrus-v** [comment]
@yvaucher thanks for review and adding odoo mock package !

I've rebase and rewords the commit.

**Review by yvaucher — APPROVED** [review]
Tested locally, seems to works fine

**Comment by lmignon** [comment]
@yvaucher @petrus-v  I tested it on a large install and I've unexpected behavior. I'm going to dive into this code to understand whether the problem is in this change or in my project.

**Comment by lmignon** [comment]
> @yvaucher @petrus-v I tested it on a large install and I've unexpected behavior. I'm going to dive into this code to understand whether the problem is in this change or in my project.

My bad, the pytest lib was still in version < 7.0. Everything is working fine. Thank you @petrus-v

**Comment by petrus-v** [comment]
> > @yvaucher @petrus-v I tested it on a large install and I've unexpected behavior. I'm going to dive into this code to understand whether the problem is in this change or in my project.
> 
> My bad, the pytest lib was still in version < 7.0. Everything is working fine. Thank you @petrus-v

Great ! thanks for testing and feedback.

**Pull request merged**
